### ISSUE TITLE
System.NotSupportedException: 'The requested security protocol is not supported.'

### ISSUE THREAD

**Issue by Nordgaren** [aalitor/AltoMultiThreadDownloadManager-master#1]
I have this code, as per the example:
public void Download()
        {
            downloadFolder = Environment.GetFolderPath(Environment.SpecialFolder.InternetCache) + @"\IE\";
            var url = @"https://drive.google.com/file/d/1yID7IOvU74Io32v1I_S2sUDxtwqEB6Yk/view?usp=sharing";
            var saveFolder = downloadFolder;
            var saveFileName = "DARK SOULS";
            var chunkFilesFolder = downloadFolder;
            var nofMaxThread = 8;
            var downloader = new MultiThreadDownloadOrganizer(url, saveFolder, saveFileName, chunkFilesFolder, nofMaxThread);
            downloader.ProgressChanged += Downloader_ProgressChanged;
            downloader.DownloadInfoReceived += Downloader_DownloadInfoReceived;
            downloader.Completed += Downloader_Completed;
            //downloader.StatusChanged += Downloader_StatusChanged;
            downloader.Start();
        }

But I get this error: System.NotSupportedException: 'The requested security protocol is not supported.'

Any idea why? I'm using WPF and .Net core 3.1

It happens on this line, btw: 
var downloader = new MultiThreadDownloadOrganizer(url, saveFolder, saveFileName, chunkFilesFolder, nofMaxThread);

**Comment by aalitor** [comment]
Hi @Nordgaren ,

Firstly your url doesnt contains the file directly, it returns an html page instead a rar file. Drive files stored in temporary urls and expires in certain periods. To download over Google Drive, you must set the proper cookies and headers in BeforeSendingRequest event, otherwise it returns an html file. You can take a look these headers and cookies using a Chrome extension e.g [CDN Headers & Cookies](https://chrome.google.com/webstore/detail/cdn-headers-cookies/obldlamadkihjlkdjblncejeblbogmnb?hl=tr) .Chrome browser integration gives us the required cookie and headers to download correctly. So you should use NativeMessaging which my library provides classes, methods and chrome extension for this. You can examine the demo app in the library to learn how native messaging should be used.

It also seems you are using an older version of the library. Please update to the latest version and try again the above methods.

Btw I could successfully downloaded the file using my demo application in the library. Chrome gave the temporary direct download link contains the file as below.

Temp Url: https://doc-00-48-docs.googleusercontent.com/docs/securesc/lsbj6u3i2broqhjlhh1rgl1pur9nv89c/lu4q7ag60dkg74gc7sfhpl6oblc7vpna/1621283475000/00455662179953955524/05815548638186256017/1yID7IOvU74Io32v1I_S2sUDxtwqEB6Yk?e=download&authuser=0&nonce=9ap3kacfvlhms&user=05815548638186256017&hash=727n1vhjb1jqtvdjuu1e9259r7logqs7

![image](https://user-images.githubusercontent.com/15199959/118552364-83761300-b767-11eb-8464-21028a1e0d15.png)

Chrome sent these headers and cookies to download:

`{
   "FileSize":0,
   "TabUrl":"https://drive.google.com/u/0/uc?export=download&confirm=47OL&id=1yID7IOvU74Io32v1I_S2sUDxtwqEB6Yk",
   "Url":"https://doc-00-48-docs.googleusercontent.com/docs/securesc/lsbj6u3i2broqhjlhh1rgl1pur9nv89c/cckird4qvkib3sc9sjkdekfmfn2iaf2u/1621284600000/00455662179953955524/05815548638186256017/1yID7IOvU74Io32v1I_S2sUDxtwqEB6Yk?e=download&authuser=0&nonce=77jcs8nncfpd6&user=05815548638186256017&hash=7q4q81u3dc47pec0eqte2t2jai94han5",
   "FileName":"parts.rar",
   "Headers":[
      {
         "Name":"Upgrade-Insecure-Requests",
         "Value":"1"
      },
      {
         "Name":"User-Agent",
         "Value":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36"
      },
      {
         "Name":"Accept",
         "Value":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"
      },
      {
         "Name":"X-Client-Data",
         "Value":"CJS2yQEIo7bJAQjEtskBCKmdygEIlqzKAQj4x8oBCOnZygEIqZ3LAQigoMsBCKygywEI3PLLARjM8ssB"
      },
      {
         "Name":"Sec-Fetch-Site",
         "Value":"cross-site"
      },
      {
         "Name":"Sec-Fetch-Mode",
         "Value":"navigate"
      },
      {
         "Name":"Sec-Fetch-User",
         "Value":"?1"
      },
      {
         "Name":"Sec-Fetch-Dest",
         "Value":"document"
      },
      {
         "Name":"sec-ch-ua",
         "Value":"\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"90\", \"Google Chrome\";v=\"90\""
      },
      {
         "Name":"sec-ch-ua-mobile",
         "Value":"?0"
      },
      {
         "Name":"Referer",
         "Value":"https://drive.google.com/"
      },
      {
         "Name":"Accept-Encoding",
         "Value":"gzip, deflate, br"
      },
      {
         "Name":"Accept-Language",
         "Value":"tr-TR,tr;q=0.9,en-US;q=0.8,en;q=0.7"
      },
      {
         "Name":"Cookie",
         "Value":"AUTH_r6g6bi1696lsg9bjdc9ud1ssvo24su70_nonce=77jcs8nncfpd6"
      }
   ]
}`

**Comment by Nordgaren** [comment]
Thank you!

**Comment by Nordgaren** [comment]
Just as a question, is there a way for this downloader to check if the file has already been partially downloaded and resume? Like, say, if the program that was using it crashed and when you started it back up, it would check first? I have tried using the resume function, and noticed that downloader.Info.AcceptRanges is true and downloader.Info.ResumeCapability is unknown for a file I'm trying to use.

Is there something serverside that needs to be enables for resuming downloads, or does the package need to handle the download from start to finish without crash for that kind of functionality?



thanks.

**Comment by aalitor** [comment]
Hi @Nordgaren,

To handle it the downloader needs partial ranges that contain start, end and remaining byte points. So you can store the HttpMultiThreadDownloader instance as serialized to json to whereever you want e.g disk, registry or settings file in your application and read it after the program reopened or when trying to resume the download again. My demo application in the library works using this method. The download can be resumed even after the program closed and opened using this method.

**Comment by Nordgaren** [comment]
@aalitor 

I was successful in saving and loading the JSons, but for some reason I can't get it to resume. I've tried both the Resume() and Start() methods, and I've even printed out the info in the Debug Console.

I am only using one instance, as the purpose of the program is to download a specific mod for a game, so I don't need a list of HttpMultiThreadDownloader. Is this because the file doesn't support chunked downloading? (This is something I'm not sure of. I would assume it does support chunked downloading, because Resumability is flagged as yes.)

Let me know if you need to see how I'm saving and loading, but I'm just using the JsonSerializer and Deserializer from Newtonsoft, and I'm pretty sure it's working because I can check the values of everything when I load in the De-serialized object.

Below is the JSon that I'm generating with Newtonsoft.

`{"UseChunk":false,"TotalBytesReceived":86337781,"Id":null,"Speed":22613940,"Progress":25.01,"ProgressString":"25.01%","Status":1,"NofActiveThreads":8,"IsActive":true,"FilePath":"C:\\Users\\Tor\\AppData\\Local\\Microsoft\\Windows\\INetCache\\IE\\DARK SOULS PREPARE TO DIE EDITION.zip","RangeDir":"C:\\Users\\Tor\\AppData\\Local\\Microsoft\\Windows\\INetCache\\IE\\\\chunks","Url":"http://20xx.io:500/temp/DarkSoulsRemastest-BETA-1.3.3-BETA.zip","Ranges":[{"Start":0,"End":44053424,"TotalBytesReceived":13548526,"IsDownloaded":false,"FileId":"cb8bab6bc4f7443796f25c36b4569f7b","Size":44053425,"Status":8,"IsIdle":false,"SaveDir":"C:\\Users\\Tor\\AppData\\Local\\Microsoft\\Windows\\INetCache\\IE\\\\chunks","FilePath":"C:\\Users\\Tor\\AppData\\Local\\Microsoft\\Windows\\INetCache\\IE\\\\chunks\\cb8bab6bc4f7443796f25c36b4569f7b","LastTry":"2021-05-23T18:57:01.9646101-07:00","LastChecksum":null},{"Start":172582048,"End":215778517,"TotalBytesReceived":12225758,"IsDownloaded":false,"FileId":"5f92c63b80a445e29f413610dde9593e","Size":43196470,"Status":8,"IsIdle":false,"SaveDir":"C:\\Users\\Tor\\AppData\\Local\\Microsoft\\Windows\\INetCache\\IE\\\\chunks","FilePath":"C:\\Users\\Tor\\AppData\\Local\\Microsoft\\Windows\\INetCache\\IE\\\\chunks\\5f92c63b80a445e29f413610dde9593e","LastTry":"2021-05-23T18:57:02.6433081-07:00","LastChecksum":null},{"Start":258873072,"End":302018583,"TotalBytesReceived":13695979,"IsDownloaded":false,"FileId":"11622c1fa16b4db18b6d4ed2648deaed","Size":43145512,"Status":8,"IsIdle":false,"SaveDir":"C:\\Users\\Tor\\AppData\\Local\\Microsoft\\Windows\\INetCache\\IE\\\\chunks","FilePath":"C:\\Users\\Tor\\AppData\\Local\\Microsoft\\Windows\\INetCache\\IE\\\\chunks\\11622c1fa16b4db18b6d4ed2648deaed","LastTry":"2021-05-23T18:57:02.6448083-07:00","LastChecksum":null},{"Start":86517186,"End":129549615,"TotalBytesReceived":11270920,"IsDownloaded":false,"FileId":"014f0d8b229946c09e784e43205e9b4b","Size":43032430,"Status":8,"IsIdle":false,"SaveDir":"C:\\Users\\Tor\\AppData\\Local\\Microsoft\\Windows\\INetCache\\IE\\\\chunks","FilePath":"C:\\Users\\Tor\\AppData\\Local\\Microsoft\\Windows\\INetCache\\IE\\\\chunks\\014f0d8b229946c09e784e43205e9b4b","LastTry":"2021-05-23T18:57:02.8268219-07:00","LastChecksum":null},{"Start":302018584,"End":345164096,"TotalBytesReceived":10811019,"IsDownloaded":false,"FileId":"7a7447a2291c49a9b6c55ec62c314025","Size":43145513,"Status":8,"IsIdle":false,"SaveDir":"C:\\Users\\Tor\\AppData\\Local\\Microsoft\\Windows\\INetCache\\IE\\\\chunks","FilePath":"C:\\Users\\Tor\\AppData\\Local\\Microsoft\\Windows\\INetCache\\IE\\\\chunks\\7a7447a2291c49a9b6c55ec62c314025","LastTry":"2021-05-23T18:57:02.8308226-07:00","LastChecksum":null},{"Start":215778518,"End":258873071,"TotalBytesReceived":6668999,"IsDownloaded":false,"FileId":"2e2bf263ee844dd1a0369a1517b91134","Size":43094554,"Status":8,"IsIdle":false,"SaveDir":"C:\\Users\\Tor\\AppData\\Local\\Microsoft\\Windows\\INetCache\\IE\\\\chunks","FilePath":"C:\\Users\\Tor\\AppData\\Local\\Microsoft\\Windows\\INetCache\\IE\\\\chunks\\2e2bf263ee844dd1a0369a1517b91134","LastTry":"2021-05-23T18:57:03.0333311-07:00","LastChecksum":null},{"Start":129549616,"End":172582047,"TotalBytesReceived":7819479,"IsDownloaded":false,"FileId":"49a3030aaf00457ca452ae903414d4b9","Size":43032432,"Status":8,"IsIdle":false,"SaveDir":"C:\\Users\\Tor\\AppData\\Local\\Microsoft\\Windows\\INetCache\\IE\\\\chunks","FilePath":"C:\\Users\\Tor\\AppData\\Local\\Microsoft\\Windows\\INetCache\\IE\\\\chunks\\49a3030aaf00457ca452ae903414d4b9","LastTry":"2021-05-23T18:57:03.0343306-07:00","LastChecksum":null},{"Start":44053425,"End":86517185,"TotalBytesReceived":10297101,"IsDownloaded":false,"FileId":"9ba2b561f8974a9e93eeb95f50f8cfef","Size":42463761,"Status":8,"IsIdle":false,"SaveDir":"C:\\Users\\Tor\\AppData\\Local\\Microsoft\\Windows\\INetCache\\IE\\\\chunks","FilePath":"C:\\Users\\Tor\\AppData\\Local\\Microsoft\\Windows\\INetCache\\IE\\\\chunks\\9ba2b561f8974a9e93eeb95f50f8cfef","LastTry":"2021-05-23T18:57:03.2181123-07:00","LastChecksum":null}],"Info":{"Url":"http://20xx.io:500/temp/DarkSoulsRemastest-BETA-1.3.3-BETA.zip","ContentSize":345164097,"AcceptRanges":true,"ServerFileName":"DarkSoulsRemastest-BETA-1.3.3-BETA.zip","ResumeCapability":1},"SaveDir":"C:\\Users\\Tor\\AppData\\Local\\Microsoft\\Windows\\INetCache\\IE\\","FlagStop":false,"NofThread":8,"SaveFileName":"DARK SOULS PREPARE TO DIE EDITION.zip","DownloadRequestMessage":null,"LastInfo":{"Url":"http://20xx.io:500/temp/DarkSoulsRemastest-BETA-1.3.3-BETA.zip","ContentSize":345164097,"AcceptRanges":true,"ServerFileName":"DarkSoulsRemastest-BETA-1.3.3-BETA.zip","ResumeCapability":-1},"LastTry":"0001-01-01T00:00:00"}`

I really appreciate your time! Thank you!

**Comment by aalitor** [comment]
Hi @Nordgaren ,

It seems you saved your instance when still downloading and `Range `status remains as `State.Downloading` as it seemed in json.  Range status has to be one of the idle statuses (`Stopped, Completed or ErrorOccured`). In this status the downloader says NofActiveThreads is 8 which is equals `NofMaxThread`, because range status is Downloading, so no threads created when calling `Resume `. So you have to ensure the download stopped or completed when you save your json.
I tried your json using the code below to change range statuses and it resumed succesfully. But this method is a bit dirty causing data corruption in the downloader instance. Best way is saving json when download stopped or completed. Try and let me know please.


```
foreach (var range in downloader.Ranges)
{
        range.Status = AltoMultiThreadDownloadManager.Enums.State.Stopped;
}
d.Resume();
```

**Comment by Nordgaren** [comment]
Oh, okay. So there's no way to implement what I'm looking for, then? I'm mainly looking for a way for the program to keep a backup of the progress in-case the end user crashes or gets disconnected while downloading (The actual file will be 3+ gigs, so it's not going to be the fastest download)

I could, I guess, stop the download every time I try to save, but right now I'm making the saved every second.

What do you think the best way to go about this is? Maybe save every 10 minutes? Would stopping and starting the download every 10 minutes have a big effect on the overall download?

I guess I can have the save check if ErrorOccured, which would cover the bases if their internet disconnects, right? How would I go about getting an efficient save if their client crashed while downloading (I don't think many peoples clients will, but I do want to cover any outliers if I can)

**Comment by Nordgaren** [comment]
Or would be be possible to make a copy of the downloader, stop it, and save that copy instead, or would that also cause corruption issues?

Obviously none of this is viable if it corrupts the download data.

**Comment by aalitor** [comment]
You can save json in the important events of downloader such as `ErrorOccured`, `Stopped`, `StatusChanged` or even `ProgressChanged ` event (but it may slow down your application). You can save json also in `FormClosed ` event of the form, but i am not sure if this event raised when application crushed and closed.

**Comment by Nordgaren** [comment]
> 
> 
> Hi @Nordgaren ,
> 
> It seems you saved your instance when still downloading and `Range `status remains as `State.Downloading` as it seemed in json. Range status has to be one of the idle statuses (`Stopped, Completed or ErrorOccured`). In this status the downloader says NofActiveThreads is 8 which is equals `NofMaxThread`, because range status is Downloading, so no threads created when calling `Resume `. So you have to ensure the download stopped or completed when you save your json.
> I tried your json using the code below to change range statuses and it resumed succesfully. But this method is a bit dirty causing data corruption in the downloader instance. Best way is saving json when download stopped or completed. Try and let me know please.
> 
> ```
> foreach (var range in downloader.Ranges)
> {
>         range.Status = AltoMultiThreadDownloadManager.Enums.State.Stopped;
> }
> d.Resume();
> ```

When you say "This method is a bit dirty causing data corruption in the downloader instance" do you mean the data in the downloader class? Does it corrupt the download as well?

How do I check if the data is corrupted?

I was thinking about trying to make a copy of the class in my save function, stopping the copy and then writing that. That way, it's stopped and saved.

Let me know! Thanks again!

**Comment by aalitor** [comment]
I mean, the downloader has some flags to control `Stopping` and `Resuming `actions. Changing the statuses manually may cause wrong assignment for those flag variables and cause the downloader to work wrong. 
Do you really need to create a copy of the instance? When your application closed just call `Stop `function and wait for `Stopped `event, then application can exit safely. You can make a block like the code below. Doesn't it fix your problem?

```
bool canAppExit = false;

void Form_Closing(object sender, FormClosingEventArgs e)
{
	if(!canAppExit)
	{
		if(downloader.NofActiveThreads > 0)
		{
			e.Cancel = true;
			downloader.Stop();
		}
	}
}

void downloader_Stopped(object sender, EventArgs e)
{
	saveDownloaderInstanceJson();
	//Downloader stopped and application can exit safely
	canAppExit = true;
	//Close application
	this.Close();
}


```

**Comment by Nordgaren** [comment]
> I mean, the downloader has some flags to control `Stopping` and `Resuming `actions. Changing the statuses manually may cause wrong assignment for those flag variables and cause the downloader to work wrong.
> Do you really need to create a copy of the instance? When your application closed just call `Stop `function and wait for `Stopped `event, then application can exit safely. You can make a block like the code below. Doesn't it fix your problem?
> 
> ```
> bool canAppExit = false;
> 
> void Form_Closing(object sender, FormClosingEventArgs e)
> {
> 	if(!canAppExit)
> 	{
> 		if(downloader.NofActiveThreads > 0)
> 		{
> 			e.Cancel = true;
> 			downloader.Stop();
> 		}
> 	}
> }
> 
> void downloader_Stopped(object sender, EventArgs e)
> {
> 	saveDownloaderInstanceJson();
> 	//Downloader stopped and application can exit safely
> 	canAppExit = true;
> 	//Close application
> 	this.Close();
> }
> ```

Well, the point of backing up periodically was to cover the incident of someone somehow closing the program without that triggering (I actually do have a bool that gets checked when the app closes).

That's why I asked. I don't really want to stop the download every 10 minutes, unless that doesn't really effect the download time, much. 

I'll test it out, actually. I just wanted to see if this was possible to do.

**Comment by aalitor** [comment]
I guess periodically saving json doesnt work properly, it may cause corruption on file chunks and final file after chunks merged. There is possibility to download and write already downloaded chunks, this will cause file corruption. You have to catch every progress change on chunks. Best way to save json without data corruption is to save it in ProgressChanged. So you can avoid to download bytes that are already downloaded and written  twice.

I think also you should find a way to catch event that closing the app for application to work safely

**Comment by Nordgaren** [comment]
> 
> 
> I guess periodically saving json doesnt work properly, it may cause corruption on file chunks and final file after chunks merged. There is possibility to download and write already downloaded chunks, this will cause file corruption. You have to catch every progress change on chunks. Best way to save json without data corruption is to save it in ProgressChanged. So you can avoid to download bytes that are already downloaded and written twice.
> 
> I think also you should find a way to catch event that closing the app for application to work safely

The problem I get with saving it on progress changed is that the event fires so much that I get an error. Usually it's because the file being written is still in use by the previous streamwriter, and I am using the streamwriter in a using statement, so I know it's being disposed.

Are there any event types that get sent per event? I don't see any. :(

save code for reference
```cs
using (StreamWriter sw = new StreamWriter($@"{ Downloader.RangeDir }\DownloadSave.txt"))
            {
                JsonSerializer serializer = new JsonSerializer();
                serializer.Serialize(sw, Downloader);
            }
````

**Comment by aalitor** [comment]
@Nordgaren ,

File operation is not safe. You can create a string type user-defined settings variable in application like `Properties.Settings.Default.DownloaderJson` and a code block like below:

```
void downloader_ProgressChanged(object sender, ProgressChangedEventArgs e)
{
    Properties.Settings.Default.DownloaderJson = JsonConvert.SerializeObject(downloader);
    Properties.Settings.Default.Save();
}


```

**Comment by Nordgaren** [comment]
So, I did try the method of writing to the settings file, but I get this problem ,now:

System.InvalidOperationException: 'Sequence contains no matching element'

I think the Resume() function is being tripped up.

This save progress function gets called every time Downloader_ProgressChanged happens

I might institute a stopwatch and try checking against the stopwatch time and save at intervals like one or five minutes

I'm using a private static instance of the class right now for the whole class, because I'm just writing something simple that downloads one very large file.


```cs
static void SaveProgress()
        {
            Downloader.Stop();
            Properties.Settings.Default.DownloaderJson = JsonConvert.SerializeObject(Downloader);
            Properties.Settings.Default.Save();
            Downloader.Resume();
       }
```

**Comment by Nordgaren** [comment]
I've also noticed that the Stop command doesn't stop the down loader right away? Is this because stop waits for a chunk to be finished? What's the best way to wait for it to stop, or would I just have to figure out a way to wire my save to the download stopped event?

I was hooking up my save method to the exit logic and even when the stop function is called, the Status is still Downloading and it does seem to keep working in the background.
