### ISSUE TITLE
Chunk files

### ISSUE THREAD

**Issue by rjclarkewp007** [aalitor/AltoMultiThreadDownloadManager-master#2]
Hi

Quick question, how can I remove the chunk files after the download is complete? or after the merge is complete?

Ideally i would like the chunk files to be removed as soon as the merge completes otherwise I will run out of space when downloading big files.
Let's say i'm downloading a 20GB zip file, this means 20GB will be taken up for the chunk files, 20GB for the merged zip file and 20GB+ for the extracted files..

**Comment by rjclarkewp007** [comment]
Just as a side note here. I've set the chunk files to be placed in a tmp folder to where the downloads are be stored.
in other words, my downloads are saved to Downloads and inside Downloads the program will create a "tmp" folder and save the chunk files here.
When the downloads is done, I am able to tell the program to remove all files inside tmp folder, but if I STOP the download and want to remove the chunk files the program cannot access the chunk files as its still in use. :(

**Comment by aalitor** [comment]
Hi @rjclarkewp007,

Have you tried to delete the temp files after the Stopped event raised?

**Comment by rjclarkewp007** [comment]
Hi, yes i have and while the download is stopped i can remove the files without any problems.
but as soon as i try and do this in code then it says the files are in use.

In other words i can manually remove the files, but not by using a code.

at this stage i have the code like this: (this does not delete anything. If i remove "try" then i will receive the error that the file/files are in use.

DirectoryInfo di = new DirectoryInfo(installpath);

                try
                {
                    foreach (FileInfo file in di.GetFiles())
                    {
                        file.Delete();
                        while (file.Exists)
                        {
                            Thread.Sleep(1000);
                            file.Refresh();
                        }
                    }
                    foreach (DirectoryInfo dir in di.GetDirectories())
                    {
                        dir.Delete(true);
                        while (dir.Exists)
                        {
                            Thread.Sleep(1000);
                            dir.Refresh();
                        }
                    }
                    Directory.Delete(installpath, true);
                }
                catch
                {

                }

**Comment by aalitor** [comment]
Hi @rjclarkewp007 ,

I have tried the code below to delete the partial files and it successfully deleted the files. What is `installpath `? Can you share your complete code to delete the files?

```
public partial class Form1 : Form
    {
        HttpMultiThreadDownloader d;
        public Form1()
        {
            InitializeComponent();
            var url = "http://ipv4.download.thinkbroadband.com/1GB.zip";
            var desktop = Environment.GetFolderPath(Environment.SpecialFolder.Desktop);

            d = new HttpMultiThreadDownloader(url, desktop, "test.zip", desktop, 8);
            d.Stopped += d_Stopped;
            d.ProgressChanged += d_ProgressChanged;
            d.Start();
        }

        void d_ProgressChanged(object sender, AltoMultiThreadDownloadManager.EventArguments.ProgressChangedEventArgs e)
        {
            progressBar1.Value = (int)e.Progress;
        }

        void d_Stopped(object sender, EventArgs e)
        {
            var d = sender as HttpMultiThreadDownloader;
            foreach (var item in d.Ranges)
            {
                File.Delete(item.FilePath);
            }
        }

        private void button1_Click(object sender, EventArgs e)
        {
            d.Stop();
        }
    }
```

**Comment by Nordgaren** [comment]
This may also work for the problem

You have to subscribe to the MergeComplete event
```
        private void Downloader_MergeCompleted(object sender, EventArgs e)
        {
            var downloader = (HttpMultiThreadDownloader)sender;
            Directory.Delete(downloader.RangeDir, true);
            Pages.Delegates.GoToZip();
        }
```
